apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: quarkus-test
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ezhang-tenant/quarkus-test/quarkus-test@sha256:2de9793869129b5f66ecbbff9d52049a23119f280436babc6967ddfa8f8d638e
        name: my-java-quarkus
        resources: {}
status: {}
