apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-test
    app.kubernetes.io/part-of: quarkus-test
  name: quarkus-testetbk
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: quarkus-test
    weight: null
status: {}
