apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quarkus-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quarkus-test
    app.kubernetes.io/part-of: quarkus-test
  name: quarkus-test
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quarkus-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quarkus-test
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ezhang-tenant/quarkus-test/quarkus-test@sha256:2de9793869129b5f66ecbbff9d52049a23119f280436babc6967ddfa8f8d638e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
